from .image_constants import ALLOWED_IMAGE_FORMATS, ALLOWED_IMAGE_SIZES
from .video_constants import ALLOWED_VIDEO_FORMATS, ALLOWED_VIDEO_SIZES

ACCEPTED_SIZES = set.union(ALLOWED_IMAGE_SIZES, ALLOWED_VIDEO_SIZES)
ACCEPTED_FORMATS = set.union(ALLOWED_IMAGE_FORMATS, ALLOWED_VIDEO_FORMATS)
